node {
    ansiColor('gnome-terminal'){
        ws {
            deleteDir()
            stage('print key') {
                withCredentials([sshUserPrivateKey(credentialsId: 'gitlab_key', keyFileVariable: 'ssh_key', passphraseVariable: '', usernameVariable: '')]) {
                    sh 'echo "$ssh_key"'
                }
            }

            stage('git clone') {
                dir('technovate') {
                    git credentialsId: 'gitlab_key', url: 'git@gitlab.com:technovate/technovate-terraform.git'
                    sh 'pwd; ls -ld'
                }
            }

            stage('config file') {
                configFileProvider([configFile(fileId: '575ced3f-cdd2-4a56-b6f2-e5039a079541', variable: 'file_var')]) {
                    sh 'cat $file_var'
                }

            }
        }
    }
}